- swagger: "2.0"
  info:
    title: Warranty Promise API
    description: A structured value representing the duration and scope of services
      that will be provided to a customer free of charge in case of a defect or malfunction
      of a product.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: warranty.promise.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /warranty-promise/:
      get:
        summary: Get Warranty Promise
        description: Returns Warranty Promise
        operationId: getWarrantyPromise
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Warranty Promise
      post:
        summary: Add Warranty Promise
        description: Add Warranty Promise
        operationId: addWarrantyPromise
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: durationofwarranty
          in: formData
          description: The duration of the warranty promise. Common unitCode values
            are ANN for year, MON for months, or DAY for days.
          required: false
          type: quantitativevalue
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: imageobject or  url
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        - name: warranty
          in: formData
          description: The warranty promise(s) included in the offer.  Supersedes warrantyPromise.
          required: false
          type: demand or offer
        - name: warrantyscope
          in: formData
          description: The scope of the warranty promise.
          required: false
          type: warrantyscope
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Warranty Promise
    /warranty-promise/{id}/:
      get:
        summary: Get Warranty Promise
        description: Returns a single Warranty Promise
        operationId: getWarrantyPromise
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Warranty Promise
      put:
        summary: Update Warranty Promise
        description: Update a single Warranty Promise
        operationId: updateWarrantyPromiseItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: durationofwarranty
          in: formData
          description: The duration of the warranty promise. Common unitCode values
            are ANN for year, MON for months, or DAY for days.
          required: false
          type: quantitativevalue
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: imageobject or  url
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        - name: warranty
          in: formData
          description: The warranty promise(s) included in the offer.  Supersedes warrantyPromise.
          required: false
          type: demand or offer
        - name: warrantyscope
          in: formData
          description: The scope of the warranty promise.
          required: false
          type: warrantyscope
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Warranty Promise
      delete:
        summary: Warranty Promise
        description: Deletes a single Warranty Promise
        operationId: deleteWarrantyPromise
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Warranty Promise
  definitions:
    item:
      properties:
      - name:
          description: additionaltype
          type: url
        description:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
      - name:
          description: alternatename
          type: text
        description:
          description: An alias for the item.
          type: text
      - name:
          description: description
          type: text
        description:
          description: A short description of the item.
          type: text
      - name:
          description: durationofwarranty
          type: quantitativevalue
        description:
          description: The duration of the warranty promise. Common unitCode values
            are ANN for year, MON for months, or DAY for days.
          type: quantitativevalue
      - name:
          description: image
          type: imageobject or  url
        description:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: imageobject or  url
      - name:
          description: mainentityofpage
          type: creativework or  url
        description:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
      - name:
          description: name
          type: text
        description:
          description: The name of the item.
          type: text
      - name:
          description: potentialaction
          type: action
        description:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          type: action
      - name:
          description: sameas
          type: url
        description:
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          type: url
      - name:
          description: url
          type: url
        description:
          description: URL of the item.
          type: url
      - name:
          description: warranty
          type: demand or offer
        description:
          description: The warranty promise(s) included in the offer.  Supersedes warrantyPromise.
          type: demand or offer
      - name:
          description: warrantyscope
          type: warrantyscope
        description:
          description: The scope of the warranty promise.
          type: warrantyscope