---
carrierRequirements: String Content
softwareRequirements: String Content
permissions: String Content
processorRequirements: String Content
availableOnDevice: String Content
featureList: String Content
applicationSubCategory: String Content
device: String Content
applicationCategory: String Content
softwareVersion: String Content
storageRequirements: !php/object "O:8:\"stdClass\":0:{}"
applicationSuite: String Content
memoryRequirements: String Content
screenshot: !php/object "O:8:\"stdClass\":0:{}"
countriesSupported: String Content
softwareHelp: !php/object "O:8:\"stdClass\":0:{}"
softwareAddOn: !php/object "O:8:\"stdClass\":0:{}"
releaseNotes: !php/object "O:8:\"stdClass\":0:{}"
supportingData: !php/object "O:8:\"stdClass\":0:{}"
requirements: String Content
countriesNotSupported: String Content
operatingSystem: String Content
fileSize: String Content
installUrl: !php/object "O:8:\"stdClass\":0:{}"
...
