---
$id: http://schema.org.apievangelist.com/schema/objects/MobileApplication.json
schema: http://json-schema.org/draft-07/schema#
description: A software application designed specifically to work well on a mobile
  device such as a telephone.
properties:
  carrierRequirements:
    description: Specifies specific carrier(s) requirements for the application (e.g.
      an application may only work on a specific carrier network).
    type: string
  softwareRequirements:
    description: 'Component dependency requirements for application. This includes
      runtime environments and shared libraries that are not included in the application
      distribution package, but required to run the application (Examples: DirectX,
      Java or .NET runtime).'
    type: string
  permissions:
    description: Permission(s) required to run the app (for example, a mobile app
      may require full internet access or may run only on wifi).
    type: string
  processorRequirements:
    description: Processor architecture required to run the application (e.g. IA64).
    type: string
  availableOnDevice:
    description: Device required to run the application. Used in cases where a specific
      make/model is required to run the application.
    type: string
  featureList:
    description: Features or modules provided by this application (and possibly required
      by other applications).
    type: string
  applicationSubCategory:
    description: Subcategory of the application, e.g.  Arcade Game .
    type: string
  device:
    description: Device required to run the application. Used in cases where a specific
      make/model is required to run the application.
    type: string
  applicationCategory:
    description: Type of software application, e.g.  Game, Multimedia .
    type: string
  softwareVersion:
    description: Version of the software instance.
    type: string
  storageRequirements:
    description: Storage requirements (free space required).
    schema:
      $ref: 'http://schema.org.apievangelist.com/schema/objects/URL'
  applicationSuite:
    description: The name of the application suite to which the application belongs
      (e.g. Excel belongs to Office).
    type: string
  memoryRequirements:
    description: Minimum memory requirements.
    type: string
  screenshot:
    description: A link to a screenshot image of the app.
    schema:
      $ref: 'http://schema.org.apievangelist.com/schema/objects/URL'
  countriesSupported:
    description: Countries for which the application is supported. You can also provide
      the two-letter ISO 3166-1 alpha-2 country code.
    type: string
  softwareHelp:
    description: Software application help.
    schema:
      $ref: 'http://schema.org.apievangelist.com/schema/objects/CreativeWork'
  softwareAddOn:
    description: Additional content for a software application.
    schema:
      $ref: 'http://schema.org.apievangelist.com/schema/objects/SoftwareApplication'
  releaseNotes:
    description: Description of what changed in this version.
    schema:
      $ref: 'http://schema.org.apievangelist.com/schema/objects/URL'
  supportingData:
    description: Supporting data for a SoftwareApplication.
    schema:
      $ref: 'http://schema.org.apievangelist.com/schema/objects/DataFeed'
  requirements:
    description: 'Component dependency requirements for application. This includes
      runtime environments and shared libraries that are not included in the application
      distribution package, but required to run the application (Examples: DirectX,
      Java or .NET runtime).'
    type: string
  countriesNotSupported:
    description: Countries for which the application is not supported. You can also
      provide the two-letter ISO 3166-1 alpha-2 country code.
    type: string
  operatingSystem:
    description: Operating systems supported (Windows 7, OSX 10.6, Android 1.6).
    type: string
  fileSize:
    description: Size of the application / package (e.g. 18MB). In the absence of
      a unit (MB, KB etc.), KB will be assumed.
    type: string
  installUrl:
    description: URL at which the app may be installed, if different from the URL
      of the item.
    schema:
      $ref: 'http://schema.org.apievangelist.com/schema/objects/URL'
...
