---
manufacturer: !php/object "O:8:\"stdClass\":0:{}"
sku: String Content
audience: !php/object "O:8:\"stdClass\":0:{}"
mpn: String Content
height: !php/object "O:8:\"stdClass\":0:{}"
gtin8: String Content
reviews: !php/object "O:8:\"stdClass\":0:{}"
aggregateRating: !php/object "O:8:\"stdClass\":0:{}"
isConsumableFor: !php/object "O:8:\"stdClass\":0:{}"
offers: !php/object "O:8:\"stdClass\":0:{}"
award: String Content
category: String Content
width: !php/object "O:8:\"stdClass\":0:{}"
awards: String Content
additionalProperty: !php/object "O:8:\"stdClass\":0:{}"
isAccessoryOrSparePartFor: !php/object "O:8:\"stdClass\":0:{}"
logo: !php/object "O:8:\"stdClass\":0:{}"
gtin14: String Content
gtin13: String Content
gtin12: String Content
material: String Content
weight: !php/object "O:8:\"stdClass\":0:{}"
depth: !php/object "O:8:\"stdClass\":0:{}"
isSimilarTo: !php/object "O:8:\"stdClass\":0:{}"
model: !php/object "O:8:\"stdClass\":0:{}"
color: String Content
isRelatedTo: !php/object "O:8:\"stdClass\":0:{}"
productID: String Content
review: !php/object "O:8:\"stdClass\":0:{}"
purchaseDate: String Content
itemCondition: !php/object "O:8:\"stdClass\":0:{}"
productionDate: String Content
brand: !php/object "O:8:\"stdClass\":0:{}"
releaseDate: String Content
sameAs: !php/object "O:8:\"stdClass\":0:{}"
url: !php/object "O:8:\"stdClass\":0:{}"
image: !php/object "O:8:\"stdClass\":0:{}"
additionalType: !php/object "O:8:\"stdClass\":0:{}"
name: String Content
identifier: !php/object "O:8:\"stdClass\":0:{}"
potentialAction: !php/object "O:8:\"stdClass\":0:{}"
mainEntityOfPage: !php/object "O:8:\"stdClass\":0:{}"
description: String Content
disambiguatingDescription: String Content
alternateName: String Content
...
