---
departureStation: !php/object "O:8:\"stdClass\":0:{}"
provider: !php/object "O:8:\"stdClass\":0:{}"
arrivalPlatform: String Content
departurePlatform: String Content
trainName: String Content
trainNumber: String Content
arrivalStation: !php/object "O:8:\"stdClass\":0:{}"
arrivalTime: String Content
departureTime: String Content
...
