title:        API Evangelist
description:  A network of research sites dedicated to the technology, business, and politics of APIs.
url:          https://apievangelist.com
raw_url: http://apievangelist.com/apis/

version:      1.1.1

author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     kramdown
permalink:    pretty
pygments:     true
highlighter:  rouge

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/blog/page:num"

categories_path : /categories.html
tags_path : /tags.html

production_url : https://apievangelist.com

image : http://s3.amazonaws.com/kinlane-productions/api-evangelist/t-shirts/KL_InApiWeTrust-1000.png
imagesecure : https://s3.amazonaws.com/kinlane-productions/api-evangelist/t-shirts/KL_InApiWeTrust-1000.png

github_user: kinlane
github_repo: api-evangelist

# spreadsheet store
contactinfo_spreadsheet_key: 1bNUVKpKl1-9k_5YNt0ix4eFKTP4t2L5DhnAtCqMAf4o
project_spreadsheet_key: 1LtOUKwV80ybYXJ1nyoQJXiAEcCfc0AoborRkYSbiLE4
service_spreadsheet_key: 1m0vghHqpTV_2zdK9dCZjioH337BdxFVCZZgOi0_e3zg
product_spreadsheet_key: 1K5GTYo3McA4WNYcvv_WPRKxp5Q8emkyKlaXKATGhQFM
partner_spreadsheet_key: 1V6zSIZPjtIWWjvipAGiA4pl5xDN4ATumfNl_UQwQakg
tool_spreadsheet_key: 1Lk0zQMV36Xn17d6-2s2CihprafXiYnwrAL6I9OBxhEs

# Footer
footer_title: API Evangelist
footer_link: http://apievangelist.com
footer_image_source: https://s3.amazonaws.com/kinlane-productions/footer/empowered-by-you-banner.png
footer_image_width: 60
