- swagger: "2.0"
  info:
    title: Payment Method API
    description: 'A payment method is a standardized procedure for transferring the
      monetary amount for a purchase. Payment methods are characterized by the legal
      and technical structures used, and by the organization or group carrying out the
      transaction. Commonly used values: http://purl.org/goodrelations/v1#ByBankTransferInAdvance
      http://purl.org/goodrelations/v1#ByInvoice http://purl.org/goodrelations/v1#Cash
      http://purl.org/goodrelations/v1#CheckInAdvance http://purl.org/goodrelations/v1#COD
      http://purl.org/goodrelations/v1#DirectDebit http://purl.org/goodrelations/v1#GoogleCheckout
      http://purl.org/goodrelations/v1#PayPal http://purl.org/goodrelations/v1#PaySwarm '
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: payment.method.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /payment-method/:
      get:
        summary: Get Payment Method
        description: Returns Payment Method
        operationId: getPaymentMethod
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/PaymentMethod'
        tags:
        - Payment Method
      post:
        summary: Add Payment Method
        description: Add Payment Method
        operationId: addPaymentMethod
        parameters:
        - name: acceptedpaymentmethod
          in: formData
          description: 'The payment method(s) accepted by seller for this offer. '
          required: false
          type: demand or offer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: appliestopaymentmethod
          in: formData
          description: 'The payment method(s) to which the payment charge specification
            applies. '
          required: false
          type: paymentchargespecification
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: imageobject or  url
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: paymentmethod
          in: formData
          description: 'The name of the credit card or other method of payment for the
            order. '
          required: false
          type: order or invoice
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: supersededby
          in: formData
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          required: false
          type: class or  property or  enumeration
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/PaymentMethod'
        tags:
        - Payment Method
    /payment-method/{id}/:
      get:
        summary: Get Payment Method
        description: Returns a single Payment Method
        operationId: getPaymentMethod
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/PaymentMethod'
        tags:
        - Payment Method
      put:
        summary: Update Payment Method
        description: Update a single Payment Method
        operationId: updatePaymentMethodItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: acceptedpaymentmethod
          in: formData
          description: 'The payment method(s) accepted by seller for this offer. '
          required: false
          type: demand or offer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: appliestopaymentmethod
          in: formData
          description: 'The payment method(s) to which the payment charge specification
            applies. '
          required: false
          type: paymentchargespecification
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: imageobject or  url
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: paymentmethod
          in: formData
          description: 'The name of the credit card or other method of payment for the
            order. '
          required: false
          type: order or invoice
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: supersededby
          in: formData
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          required: false
          type: class or  property or  enumeration
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/PaymentMethod'
        tags:
        - Payment Method
      delete:
        summary: Payment Method
        description: Deletes a single Payment Method
        operationId: deletePaymentMethod
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/PaymentMethod'
        tags:
        - Payment Method
  definitions:
    PaymentMethod:
      properties:
        acceptedpaymentmethod:
          description: 'The payment method(s) accepted by seller for this offer. '
          type: demand or offer
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        alternatename:
          description: An alias for the item.
          type: text
        appliestopaymentmethod:
          description: 'The payment method(s) to which the payment charge specification
            applies. '
          type: paymentchargespecification
        description:
          description: A short description of the item.
          type: text
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: imageobject or  url
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
        name:
          description: The name of the item.
          type: text
        paymentmethod:
          description: 'The name of the credit card or other method of payment for the
            order. '
          type: order or invoice
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        supersededby:
          description: Relates a term (i.e. a property, class or enumeration) to one
            that supersedes it.
          type: class or  property or  enumeration
        url:
          description: URL of the item.
          type: url