- swagger: "2.0"
  info:
    title: Role API
    description: Represents additional information about a relationship or property.
      For example a Role can be used to say that a member role linking some SportsTeam
      to a player occurred during a particular time period. Or that a Persons actor
      role in a Movie was for some particular characterName. Such properties can be
      attached to a Role entity, which is then associated with the main entities using
      ordinary properties like member or actor. See also blog post.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: role.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /role/:
      get:
        summary: Get Role
        description: Returns Role
        operationId: getRole
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Role
      post:
        summary: Add Role
        description: Add Role
        operationId: addRole
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: enddate
          in: formData
          description: The end date and time of the item (in ISO 8601 date format).
          required: false
          type: date
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: url or  creativework
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: rolename
          in: formData
          description: A role played, performed or filled by a person or organization.
            For example, the team of creators for a comic book might fill the roles
            named 'inker', 'penciller', and 'letterer'; or an athlete in a SportsTeam
            might play in the position named 'Quarterback'. Supersedes namedPosition.
          required: false
          type: text or  url
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: startdate
          in: formData
          description: The start date and time of the item (in ISO 8601 date format).
          required: false
          type: date
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Role
    /role/{id}/:
      get:
        summary: Get Role
        description: Returns a single Role
        operationId: getRole
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Role
      put:
        summary: Update Role
        description: Update a single Role
        operationId: updateRoleItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: enddate
          in: formData
          description: The end date and time of the item (in ISO 8601 date format).
          required: false
          type: date
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: url or  creativework
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: rolename
          in: formData
          description: A role played, performed or filled by a person or organization.
            For example, the team of creators for a comic book might fill the roles
            named 'inker', 'penciller', and 'letterer'; or an athlete in a SportsTeam
            might play in the position named 'Quarterback'. Supersedes namedPosition.
          required: false
          type: text or  url
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: startdate
          in: formData
          description: The start date and time of the item (in ISO 8601 date format).
          required: false
          type: date
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Role
      delete:
        summary: Role
        description: Deletes a single Role
        operationId: deleteRole
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Role
  definitions:
    item:
      properties:
      - name:
          description: additionaltype
          type: url
        description:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
      - name:
          description: alternatename
          type: text
        description:
          description: An alias for the item.
          type: text
      - name:
          description: description
          type: text
        description:
          description: A short description of the item.
          type: text
      - name:
          description: enddate
          type: date
        description:
          description: The end date and time of the item (in ISO 8601 date format).
          type: date
      - name:
          description: image
          type: url or  imageobject
        description:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
      - name:
          description: mainentityofpage
          type: url or  creativework
        description:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: url or  creativework
      - name:
          description: name
          type: text
        description:
          description: The name of the item.
          type: text
      - name:
          description: potentialaction
          type: action
        description:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          type: action
      - name:
          description: rolename
          type: text or  url
        description:
          description: A role played, performed or filled by a person or organization.
            For example, the team of creators for a comic book might fill the roles
            named 'inker', 'penciller', and 'letterer'; or an athlete in a SportsTeam
            might play in the position named 'Quarterback'. Supersedes namedPosition.
          type: text or  url
      - name:
          description: sameas
          type: url
        description:
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          type: url
      - name:
          description: startdate
          type: date
        description:
          description: The start date and time of the item (in ISO 8601 date format).
          type: date
      - name:
          description: url
          type: url
        description:
          description: URL of the item.
          type: url