- swagger: "2.0"
  info:
    title: Medical Study API
    description: 'A medical study is an umbrella type covering all kinds of research
      studies relating to human medicine or health, including observational studies
      and interventional trials and registries, randomized, controlled or not. When
      the specific type of study is known, use one of the extensions of this type, such
      as MedicalTrial or MedicalObservationalStudy. Also, note that this type should
      be used to mark up data that describes the study itself; to tag an article that
      publishes the results of a study, use MedicalScholarlyArticle. Note: use the code
      property of MedicalEntity to store study IDs, e.g. clinicaltrials.gov ID.'
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: medical.study.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /medical-study/:
      get:
        summary: Get Medical Study
        description: Returns Medical Study
        operationId: getMedicalStudy
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Medical Study
      post:
        summary: Add Medical Study
        description: Add Medical Study
        operationId: addMedicalStudy
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: outcome
          in: formData
          description: Expected or actual outcomes of the study.
          required: false
          type: text
        - name: population
          in: formData
          description: Any characteristics of the population used in the study, e.g.
            'males under 65'.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: sponsor
          in: formData
          description: Sponsor of the study.
          required: false
          type: organization
        - name: status
          in: formData
          description: The status of the study (enumerated).
          required: false
          type: medicalstudystatus
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: studylocation
          in: formData
          description: The location in which the study is taking/took place.
          required: false
          type: administrativearea
        - name: studysubject
          in: formData
          description: A subject of the study, i.e. one of the medical conditions, therapies,
            devices, drugs, etc. investigated by the study.
          required: false
          type: medicalentity
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Medical Study
    /medical-study/{id}/:
      get:
        summary: Get Medical Study
        description: Returns a single Medical Study
        operationId: getMedicalStudy
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Medical Study
      put:
        summary: Update Medical Study
        description: Update a single Medical Study
        operationId: updateMedicalStudyItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: outcome
          in: formData
          description: Expected or actual outcomes of the study.
          required: false
          type: text
        - name: population
          in: formData
          description: Any characteristics of the population used in the study, e.g.
            'males under 65'.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: sponsor
          in: formData
          description: Sponsor of the study.
          required: false
          type: organization
        - name: status
          in: formData
          description: The status of the study (enumerated).
          required: false
          type: medicalstudystatus
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: studylocation
          in: formData
          description: The location in which the study is taking/took place.
          required: false
          type: administrativearea
        - name: studysubject
          in: formData
          description: A subject of the study, i.e. one of the medical conditions, therapies,
            devices, drugs, etc. investigated by the study.
          required: false
          type: medicalentity
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Medical Study
      delete:
        summary: Medical Study
        description: Deletes a single Medical Study
        operationId: deleteMedicalStudy
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Medical Study
  definitions:
    item:
      properties:
      - name:
          description: additionaltype
          type: url
        description:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
      - name:
          description: alternatename
          type: text
        description:
          description: An alias for the item.
          type: text
      - name:
          description: code
          type: medicalcode
        description:
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          type: medicalcode
      - name:
          description: description
          type: text
        description:
          description: A short description of the item.
          type: text
      - name:
          description: guideline
          type: medicalguideline
        description:
          description: A medical guideline related to this entity.
          type: medicalguideline
      - name:
          description: image
          type: url or  imageobject
        description:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
      - name:
          description: mainentityofpage
          type: creativework or  url
        description:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
      - name:
          description: medicinesystem
          type: medicinesystem
        description:
          description: The system of medicine that includes this MedicalEntity, for
            example 'evidence-based', 'homeopathic', 'chiropractic', etc.
          type: medicinesystem
      - name:
          description: name
          type: text
        description:
          description: The name of the item.
          type: text
      - name:
          description: outcome
          type: text
        description:
          description: Expected or actual outcomes of the study.
          type: text
      - name:
          description: population
          type: text
        description:
          description: Any characteristics of the population used in the study, e.g.
            'males under 65'.
          type: text
      - name:
          description: potentialaction
          type: action
        description:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          type: action
      - name:
          description: recognizingauthority
          type: organization
        description:
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          type: organization
      - name:
          description: relevantspecialty
          type: medicalspecialty
        description:
          description: If applicable, a medical specialty in which this entity is relevant.
          type: medicalspecialty
      - name:
          description: sameas
          type: url
        description:
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          type: url
      - name:
          description: sponsor
          type: organization
        description:
          description: Sponsor of the study.
          type: organization
      - name:
          description: status
          type: medicalstudystatus
        description:
          description: The status of the study (enumerated).
          type: medicalstudystatus
      - name:
          description: study
          type: medicalstudy
        description:
          description: A medical study or trial related to this entity.
          type: medicalstudy
      - name:
          description: studylocation
          type: administrativearea
        description:
          description: The location in which the study is taking/took place.
          type: administrativearea
      - name:
          description: studysubject
          type: medicalentity
        description:
          description: A subject of the study, i.e. one of the medical conditions, therapies,
            devices, drugs, etc. investigated by the study.
          type: medicalentity
      - name:
          description: url
          type: url
        description:
          description: URL of the item.
          type: url