- swagger: "2.0"
  info:
    title: Medical Sign Or Symptom API
    description: Any indication of the existence of a medical condition or disease.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: medical.sign.or.symptom.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /medical-sign-or-symptom/:
      get:
        summary: Get Medical Sign Or Symptom
        description: Returns Medical Sign Or Symptom
        operationId: getMedicalSignOrSymptom
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalSignOrSymptom'
        tags:
        - Medical Sign Or Symptom
      post:
        summary: Add Medical Sign Or Symptom
        description: Add Medical Sign Or Symptom
        operationId: addMedicalSignOrSymptom
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: cause
          in: formData
          description: An underlying cause. More specifically, one of the causative
            agent(s) that are most directly responsible for the pathophysiologic process
            that eventually results in the occurrence.
          required: false
          type: medicalcause
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: distinguishingsign
          in: formData
          description: 'One of a set of signs and symptoms that can be used to distinguish
            this diagnosis from others in the differential diagnosis. '
          required: false
          type: ddxelement
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: possibletreatment
          in: formData
          description: A possible treatment to address this condition, sign or symptom.
          required: false
          type: medicaltherapy
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: signorsymptom
          in: formData
          description: 'A sign or symptom of this condition. Signs are objective or
            physically observable manifestations of the medical condition while symptoms
            are the subjective experience of the medical condition. '
          required: false
          type: medicalcondition
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalSignOrSymptom'
        tags:
        - Medical Sign Or Symptom
    /medical-sign-or-symptom/{id}/:
      get:
        summary: Get Medical Sign Or Symptom
        description: Returns a single Medical Sign Or Symptom
        operationId: getMedicalSignOrSymptom
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalSignOrSymptom'
        tags:
        - Medical Sign Or Symptom
      put:
        summary: Update Medical Sign Or Symptom
        description: Update a single Medical Sign Or Symptom
        operationId: updateMedicalSignOrSymptomItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: cause
          in: formData
          description: An underlying cause. More specifically, one of the causative
            agent(s) that are most directly responsible for the pathophysiologic process
            that eventually results in the occurrence.
          required: false
          type: medicalcause
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: distinguishingsign
          in: formData
          description: 'One of a set of signs and symptoms that can be used to distinguish
            this diagnosis from others in the differential diagnosis. '
          required: false
          type: ddxelement
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: possibletreatment
          in: formData
          description: A possible treatment to address this condition, sign or symptom.
          required: false
          type: medicaltherapy
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: signorsymptom
          in: formData
          description: 'A sign or symptom of this condition. Signs are objective or
            physically observable manifestations of the medical condition while symptoms
            are the subjective experience of the medical condition. '
          required: false
          type: medicalcondition
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalSignOrSymptom'
        tags:
        - Medical Sign Or Symptom
      delete:
        summary: Medical Sign Or Symptom
        description: Deletes a single Medical Sign Or Symptom
        operationId: deleteMedicalSignOrSymptom
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalSignOrSymptom'
        tags:
        - Medical Sign Or Symptom
  definitions:
    MedicalSignOrSymptom:
      properties:
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        alternatename:
          description: An alias for the item.
          type: text
        cause:
          description: An underlying cause. More specifically, one of the causative
            agent(s) that are most directly responsible for the pathophysiologic process
            that eventually results in the occurrence.
          type: medicalcause
        code:
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          type: medicalcode
        description:
          description: A short description of the item.
          type: text
        distinguishingsign:
          description: 'One of a set of signs and symptoms that can be used to distinguish
            this diagnosis from others in the differential diagnosis. '
          type: ddxelement
        guideline:
          description: A medical guideline related to this entity.
          type: medicalguideline
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
        medicinesystem:
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          type: medicinesystem
        name:
          description: The name of the item.
          type: text
        possibletreatment:
          description: A possible treatment to address this condition, sign or symptom.
          type: medicaltherapy
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        recognizingauthority:
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          type: organization
        relevantspecialty:
          description: If applicable, a medical specialty in which this entity is relevant.
          type: medicalspecialty
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        signorsymptom:
          description: 'A sign or symptom of this condition. Signs are objective or
            physically observable manifestations of the medical condition while symptoms
            are the subjective experience of the medical condition. '
          type: medicalcondition
        study:
          description: A medical study or trial related to this entity.
          type: medicalstudy
        url:
          description: URL of the item.
          type: url