- "{\n\t\"swagger\": \"2.0\",\n\t\"info\": {\n\t\t\"title\": \"Distance API\",\n\t\t\"description\":
    \"Properties that take Distances as values are of the form \\'&lt;Number&gt; &lt;Length
    unit of measure&gt;\\'. E.g., \\'7 ft\\'.\",\n\t\t\"termsOfService\": \"http://apievangelist.com/terms-of-service.html\",\n\t\t\"version\":
    \"v1\"\n\t},\n\t\"host\": \"distance.example.com\",\n\t\"basePath\": \"/\",\n\t\"schemes\":
    [\"http\"],\n\t\"produces\": [\"application/json\"],\n\t\"paths\": {\n\t\t\"/distance/\":
    {\n\t\t\t\"get\": {\n\t\t\t\t\"summary\": \"Get Distance\",\n\t\t\t\t\"description\":
    \"Returns Distance\",\n\t\t\t\t\"operationId\": \"getDistance\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"q\",\n\t\t\t\t\t\"in\": \"query\",\n\t\t\t\t\t\"description\":
    \"Keyword search for item\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"string\"\n\t\t\t\t}],\n\t\t\t\t\"responses\": {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\":
    \"A successful response.\",\n\t\t\t\t\t\t\"schema\": {\n\t\t\t\t\t\t\t\"type\":
    \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\": \"#/definitions/Distance\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Distance\"]\n\t\t\t},\n\t\t\t\"post\": {\n\t\t\t\t\"summary\": \"Add Distance\",\n\t\t\t\t\"description\":
    \"Add Distance\",\n\t\t\t\t\"operationId\": \"addDistance\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"additionaltype\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"An additional type for the item, typically used for adding more specific types
    from external vocabularies in microdata syntax. This is a relationship between something
    and a class that the thing is in. In RDFa syntax, it is better to use the native
    RDFa syntax - the \\'typeof\\' attribute - for multiple types. Schema.org tools
    may have only weaker understanding of extra types, in particular those defined externally.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"alternatename\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"An alias for the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"depth\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The depth of the item. \",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"visualartwork or product\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"description\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"A
    short description of the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"distance\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The distance travelled, e.g. exercising
    or travelling. \",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"exerciseaction
    or travelaction\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"flightdistance\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The distance of the flight. \",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"flight\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"georadius\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"Indicates
    the approximate radius of a GeoCircle (metres unless indicated otherwise via Distance
    notation). \",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"geocircle\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"height\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"The height
    of the item. \",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"person or
    visualartwork or product or mediaobject\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"image\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"An image
    of the item. This can be a URL or a fully described ImageObject.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url or  imageobject\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"mainentityofpage\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a page (or other CreativeWork) for which this thing is the main entity
    being described.            See background notes for details.       Inverse property:
    mainEntity.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"creativework
    or  url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"name\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The name of the item.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"potentialaction\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a potential Action, which describes an idealized action in which this
    thing would play an \\'object\\' role.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"action\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"sameas\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"URL of a reference Web page that unambiguously
    indicates the item\\'s identity. E.g. the URL of the item\\'s Wikipedia page, Freebase
    page, or official website.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"url\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"URL of the item.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"width\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"The width
    of the item. \",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"visualartwork
    or product or mediaobject\"\n\t\t\t\t}],\n\t\t\t\t\"responses\": {\n\t\t\t\t\t\"200\":
    {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/Distance\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Distance\"]\n\t\t\t}\n\t\t},\n\t\t\"/distance/{id}/\": {\n\t\t\t\"get\": {\n\t\t\t\t\"summary\":
    \"Get Distance\",\n\t\t\t\t\"description\": \"Returns a single Distance\",\n\t\t\t\t\"operationId\":
    \"getDistance\",\n\t\t\t\t\"parameters\": [{\n\t\t\t\t\t\"name\": \"id\",\n\t\t\t\t\t\"in\":
    \"path\",\n\t\t\t\t\t\"description\": \"Unique id for item\",\n\t\t\t\t\t\"required\":
    true,\n\t\t\t\t\t\"type\": \"integer\"\n\t\t\t\t}],\n\t\t\t\t\"responses\": {\n\t\t\t\t\t\"200\":
    {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/Distance\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Distance\"]\n\t\t\t},\n\t\t\t\"put\": {\n\t\t\t\t\"summary\": \"Update Distance\",\n\t\t\t\t\"description\":
    \"Update a single Distance\",\n\t\t\t\t\"operationId\": \"updateDistanceItem\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"id\",\n\t\t\t\t\t\"in\": \"path\",\n\t\t\t\t\t\"description\":
    \"Unique id for item\",\n\t\t\t\t\t\"required\": true,\n\t\t\t\t\t\"type\": \"integer\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"additionaltype\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"An additional type for the item, typically used for adding more specific types
    from external vocabularies in microdata syntax. This is a relationship between something
    and a class that the thing is in. In RDFa syntax, it is better to use the native
    RDFa syntax - the \\'typeof\\' attribute - for multiple types. Schema.org tools
    may have only weaker understanding of extra types, in particular those defined externally.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"alternatename\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"An alias for the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"depth\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The depth of the item. \",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"visualartwork or product\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"description\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"A
    short description of the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"distance\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The distance travelled, e.g. exercising
    or travelling. \",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"exerciseaction
    or travelaction\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"flightdistance\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The distance of the flight. \",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"flight\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"georadius\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"Indicates
    the approximate radius of a GeoCircle (metres unless indicated otherwise via Distance
    notation). \",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"geocircle\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"height\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"The height
    of the item. \",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"person or
    visualartwork or product or mediaobject\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"image\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"An image
    of the item. This can be a URL or a fully described ImageObject.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url or  imageobject\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"mainentityofpage\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a page (or other CreativeWork) for which this thing is the main entity
    being described.            See background notes for details.       Inverse property:
    mainEntity.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"creativework
    or  url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"name\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The name of the item.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"potentialaction\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a potential Action, which describes an idealized action in which this
    thing would play an \\'object\\' role.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"action\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"sameas\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"URL of a reference Web page that unambiguously
    indicates the item\\'s identity. E.g. the URL of the item\\'s Wikipedia page, Freebase
    page, or official website.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"url\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"URL of the item.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"width\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"The width
    of the item. \",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"visualartwork
    or product or mediaobject\"\n\t\t\t\t}],\n\t\t\t\t\"responses\": {\n\t\t\t\t\t\"200\":
    {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/Distance\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Distance\"]\n\t\t\t},\n\t\t\t\"delete\": {\n\t\t\t\t\"summary\": \"Distance\",\n\t\t\t\t\"description\":
    \"Deletes a single Distance\",\n\t\t\t\t\"operationId\": \"deleteDistance\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"id\",\n\t\t\t\t\t\"in\": \"path\",\n\t\t\t\t\t\"description\":
    \"Unique id for item\",\n\t\t\t\t\t\"required\": true,\n\t\t\t\t\t\"type\": \"integer\"\n\t\t\t\t}],\n\t\t\t\t\"responses\":
    {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/Distance\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Distance\"]\n\t\t\t}\n\t\t}\n\t},\n\t\"definitions\": {\n\t\t\"Distance\": {\n\t\t\t\"properties\":
    {\n\t\t\t\t\"additionaltype\": {\n\t\t\t\t\t\"description\": \"An additional type
    for the item, typically used for adding more specific types from external vocabularies
    in microdata syntax. This is a relationship between something and a class that the
    thing is in. In RDFa syntax, it is better to use the native RDFa syntax - the \\'typeof\\'
    attribute - for multiple types. Schema.org tools may have only weaker understanding
    of extra types, in particular those defined externally.\",\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t\"alternatename\": {\n\t\t\t\t\t\"description\": \"An
    alias for the item.\",\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t\"depth\":
    {\n\t\t\t\t\t\"description\": \"The depth of the item. \",\n\t\t\t\t\t\"type\":
    \"visualartwork or product\"\n\t\t\t\t},\n\t\t\t\t\"description\": {\n\t\t\t\t\t\"description\":
    \"A short description of the item.\",\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t\"distance\":
    {\n\t\t\t\t\t\"description\": \"The distance travelled, e.g. exercising or travelling.
    \",\n\t\t\t\t\t\"type\": \"exerciseaction or travelaction\"\n\t\t\t\t},\n\t\t\t\t\"flightdistance\":
    {\n\t\t\t\t\t\"description\": \"The distance of the flight. \",\n\t\t\t\t\t\"type\":
    \"flight\"\n\t\t\t\t},\n\t\t\t\t\"georadius\": {\n\t\t\t\t\t\"description\": \"Indicates
    the approximate radius of a GeoCircle (metres unless indicated otherwise via Distance
    notation). \",\n\t\t\t\t\t\"type\": \"geocircle\"\n\t\t\t\t},\n\t\t\t\t\"height\":
    {\n\t\t\t\t\t\"description\": \"The height of the item. \",\n\t\t\t\t\t\"type\":
    \"person or visualartwork or product or mediaobject\"\n\t\t\t\t},\n\t\t\t\t\"image\":
    {\n\t\t\t\t\t\"description\": \"An image of the item. This can be a URL or a fully
    described ImageObject.\",\n\t\t\t\t\t\"type\": \"url or  imageobject\"\n\t\t\t\t},\n\t\t\t\t\"mainentityofpage\":
    {\n\t\t\t\t\t\"description\": \"Indicates a page (or other CreativeWork) for which
    this thing is the main entity being described.            See background notes for
    details.       Inverse property: mainEntity.\",\n\t\t\t\t\t\"type\": \"creativework
    or  url\"\n\t\t\t\t},\n\t\t\t\t\"name\": {\n\t\t\t\t\t\"description\": \"The name
    of the item.\",\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t\"potentialaction\":
    {\n\t\t\t\t\t\"description\": \"Indicates a potential Action, which describes an
    idealized action in which this thing would play an \\'object\\' role.\",\n\t\t\t\t\t\"type\":
    \"action\"\n\t\t\t\t},\n\t\t\t\t\"sameas\": {\n\t\t\t\t\t\"description\": \"URL
    of a reference Web page that unambiguously indicates the item\\'s identity. E.g.
    the URL of the item\\'s Wikipedia page, Freebase page, or official website.\",\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t\"url\": {\n\t\t\t\t\t\"description\": \"URL of the
    item.\",\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t},\n\t\t\t\t\"width\": {\n\t\t\t\t\t\"description\":
    \"The width of the item. \",\n\t\t\t\t\t\"type\": \"visualartwork or product or
    mediaobject\"\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n}"