- swagger: "2.0"
  info:
    title: Seat API
    description: Used to describe a seat, such as a reserved seat in an event reservation.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: seat.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /seat/:
      get:
        summary: Get Seat
        description: Returns Seat
        operationId: getSeat
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/Seat'
        tags:
        - Seat
      post:
        summary: Add Seat
        description: Add Seat
        operationId: addSeat
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: seatingtype
          in: formData
          description: The type/class of the seat.
          required: false
          type: qualitativevalue or  text
        - name: seatnumber
          in: formData
          description: The location of the reserved seat (e.g., 27).
          required: false
          type: text
        - name: seatrow
          in: formData
          description: The row location of the reserved seat (e.g., B).
          required: false
          type: text
        - name: seatsection
          in: formData
          description: The section location of the reserved seat (e.g. Orchestra).
          required: false
          type: text
        - name: ticketedseat
          in: formData
          description: 'The seat associated with the ticket. '
          required: false
          type: ticket
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/Seat'
        tags:
        - Seat
    /seat/{id}/:
      get:
        summary: Get Seat
        description: Returns a single Seat
        operationId: getSeat
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/Seat'
        tags:
        - Seat
      put:
        summary: Update Seat
        description: Update a single Seat
        operationId: updateSeatItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: seatingtype
          in: formData
          description: The type/class of the seat.
          required: false
          type: qualitativevalue or  text
        - name: seatnumber
          in: formData
          description: The location of the reserved seat (e.g., 27).
          required: false
          type: text
        - name: seatrow
          in: formData
          description: The row location of the reserved seat (e.g., B).
          required: false
          type: text
        - name: seatsection
          in: formData
          description: The section location of the reserved seat (e.g. Orchestra).
          required: false
          type: text
        - name: ticketedseat
          in: formData
          description: 'The seat associated with the ticket. '
          required: false
          type: ticket
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/Seat'
        tags:
        - Seat
      delete:
        summary: Seat
        description: Deletes a single Seat
        operationId: deleteSeat
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/Seat'
        tags:
        - Seat
  definitions:
    Seat:
      properties:
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        alternatename:
          description: An alias for the item.
          type: text
        description:
          description: A short description of the item.
          type: text
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
        name:
          description: The name of the item.
          type: text
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        seatingtype:
          description: The type/class of the seat.
          type: qualitativevalue or  text
        seatnumber:
          description: The location of the reserved seat (e.g., 27).
          type: text
        seatrow:
          description: The row location of the reserved seat (e.g., B).
          type: text
        seatsection:
          description: The section location of the reserved seat (e.g. Orchestra).
          type: text
        ticketedseat:
          description: 'The seat associated with the ticket. '
          type: ticket
        url:
          description: URL of the item.
          type: url