- swagger: "2.0"
  info:
    title: Anatomical System API
    description: An anatomical system is a group of anatomical structures that work
      together to perform a certain task. Anatomical systems, such as organ systems,
      are one organizing principle of anatomy, and can includes circulatory, digestive,
      endocrine, integumentary, immune, lymphatic, muscular, nervous, reproductive,
      respiratory, skeletal, urinary, vestibular, and other systems.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: anatomical.system.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /anatomical-system/:
      get:
        summary: Get Anatomical System
        description: Returns Anatomical System
        operationId: getAnatomicalSystem
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/AnatomicalSystem'
        tags:
        - Anatomical System
      post:
        summary: Add Anatomical System
        description: Add Anatomical System
        operationId: addAnatomicalSystem
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: associatedanatomy
          in: formData
          description: 'The anatomy of the underlying organ system or structures associated
            with this entity. '
          required: false
          type: physicalactivity or medicalcondition
        - name: associatedpathophysiology
          in: formData
          description: If applicable, a description of the pathophysiology associated
            with the anatomical system, including potential abnormal changes in the
            mechanical, physical, and biochemical functions of the system.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: comprisedof
          in: formData
          description: The underlying anatomical structures, such as organs, that comprise
            the anatomical system.
          required: false
          type: anatomicalsystem or  anatomicalstructure
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: url or  creativework
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: partofsystem
          in: formData
          description: 'The anatomical or organ system that this structure is part of. '
          required: false
          type: anatomicalstructure
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: regiondrained
          in: formData
          description: 'The anatomical or organ system drained by this vessel; generally
            refers to a specific part of an organ. '
          required: false
          type: vein or lymphaticvessel
        - name: relatedanatomy
          in: formData
          description: 'Anatomical systems or structures that relate to the superficial
            anatomy. '
          required: false
          type: superficialanatomy
        - name: relatedcondition
          in: formData
          description: A medical condition associated with this anatomy.
          required: false
          type: medicalcondition
        - name: relatedstructure
          in: formData
          description: Related anatomical structure(s) that are not part of the system
            but relate or connect to it, such as vascular bundles associated with an
            organ system.
          required: false
          type: anatomicalstructure
        - name: relatedtherapy
          in: formData
          description: A medical therapy related to this anatomy.
          required: false
          type: medicaltherapy
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/AnatomicalSystem'
        tags:
        - Anatomical System
    /anatomical-system/{id}/:
      get:
        summary: Get Anatomical System
        description: Returns a single Anatomical System
        operationId: getAnatomicalSystem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/AnatomicalSystem'
        tags:
        - Anatomical System
      put:
        summary: Update Anatomical System
        description: Update a single Anatomical System
        operationId: updateAnatomicalSystemItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: associatedanatomy
          in: formData
          description: 'The anatomy of the underlying organ system or structures associated
            with this entity. '
          required: false
          type: physicalactivity or medicalcondition
        - name: associatedpathophysiology
          in: formData
          description: If applicable, a description of the pathophysiology associated
            with the anatomical system, including potential abnormal changes in the
            mechanical, physical, and biochemical functions of the system.
          required: false
          type: text
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: comprisedof
          in: formData
          description: The underlying anatomical structures, such as organs, that comprise
            the anatomical system.
          required: false
          type: anatomicalsystem or  anatomicalstructure
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: url or  creativework
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: partofsystem
          in: formData
          description: 'The anatomical or organ system that this structure is part of. '
          required: false
          type: anatomicalstructure
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: regiondrained
          in: formData
          description: 'The anatomical or organ system drained by this vessel; generally
            refers to a specific part of an organ. '
          required: false
          type: vein or lymphaticvessel
        - name: relatedanatomy
          in: formData
          description: 'Anatomical systems or structures that relate to the superficial
            anatomy. '
          required: false
          type: superficialanatomy
        - name: relatedcondition
          in: formData
          description: A medical condition associated with this anatomy.
          required: false
          type: medicalcondition
        - name: relatedstructure
          in: formData
          description: Related anatomical structure(s) that are not part of the system
            but relate or connect to it, such as vascular bundles associated with an
            organ system.
          required: false
          type: anatomicalstructure
        - name: relatedtherapy
          in: formData
          description: A medical therapy related to this anatomy.
          required: false
          type: medicaltherapy
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/AnatomicalSystem'
        tags:
        - Anatomical System
      delete:
        summary: Anatomical System
        description: Deletes a single Anatomical System
        operationId: deleteAnatomicalSystem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/AnatomicalSystem'
        tags:
        - Anatomical System
  definitions:
    AnatomicalSystem:
      properties:
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        alternatename:
          description: An alias for the item.
          type: text
        associatedanatomy:
          description: 'The anatomy of the underlying organ system or structures associated
            with this entity. '
          type: physicalactivity or medicalcondition
        associatedpathophysiology:
          description: If applicable, a description of the pathophysiology associated
            with the anatomical system, including potential abnormal changes in the
            mechanical, physical, and biochemical functions of the system.
          type: text
        code:
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          type: medicalcode
        comprisedof:
          description: The underlying anatomical structures, such as organs, that comprise
            the anatomical system.
          type: anatomicalsystem or  anatomicalstructure
        description:
          description: A short description of the item.
          type: text
        guideline:
          description: A medical guideline related to this entity.
          type: medicalguideline
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: url or  creativework
        medicinesystem:
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          type: medicinesystem
        name:
          description: The name of the item.
          type: text
        partofsystem:
          description: 'The anatomical or organ system that this structure is part of. '
          type: anatomicalstructure
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        recognizingauthority:
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          type: organization
        regiondrained:
          description: 'The anatomical or organ system drained by this vessel; generally
            refers to a specific part of an organ. '
          type: vein or lymphaticvessel
        relatedanatomy:
          description: 'Anatomical systems or structures that relate to the superficial
            anatomy. '
          type: superficialanatomy
        relatedcondition:
          description: A medical condition associated with this anatomy.
          type: medicalcondition
        relatedstructure:
          description: Related anatomical structure(s) that are not part of the system
            but relate or connect to it, such as vascular bundles associated with an
            organ system.
          type: anatomicalstructure
        relatedtherapy:
          description: A medical therapy related to this anatomy.
          type: medicaltherapy
        relevantspecialty:
          description: If applicable, a medical specialty in which this entity is relevant.
          type: medicalspecialty
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        study:
          description: A medical study or trial related to this entity.
          type: medicalstudy
        url:
          description: URL of the item.
          type: url