- swagger: "2.0"
  info:
    title: Geo Circle API
    description: 'A GeoCircle is a GeoShape representing a circular geographic area.
      As it is a GeoShape it provides the simple textual property ''circle'', but also
      allows the combination of postalCode alongside geoRadius. The center of the circle
      can be indicated via the ''geoMidpoint'' property, or more approximately using
      ''address'', ''postalCode''. '
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: geo.circle.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /geo-circle/:
      get:
        summary: Get Geo Circle
        description: Returns Geo Circle
        operationId: getGeoCircle
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Geo Circle
      post:
        summary: Add Geo Circle
        description: Add Geo Circle
        operationId: addGeoCircle
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: address
          in: formData
          description: Physical address of the item.
          required: false
          type: text or  postaladdress
        - name: addresscountry
          in: formData
          description: The country. For example, USA. You can also provide the two-letter
            ISO 3166-1 alpha-2 country code.
          required: false
          type: text or  country
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: box
          in: formData
          description: A box is the area enclosed by the rectangle formed by two points.
            The first point is the lower corner, the second point is the upper corner.
            A box is expressed as two points separated by a space character.
          required: false
          type: text
        - name: circle
          in: formData
          description: A circle is the circular region of a specified radius centered
            at a specified latitude and longitude. A circle is expressed as a pair followed
            by a radius in meters.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: elevation
          in: formData
          description: The elevation of a location (WGS 84).
          required: false
          type: text or  number
        - name: geomidpoint
          in: formData
          description: Indicates the GeoCoordinates at the centre of a GeoShape e.g.
            GeoCircle.
          required: false
          type: geocoordinates
        - name: georadius
          in: formData
          description: Indicates the approximate radius of a GeoCircle (metres unless
            indicated otherwise via Distance notation).
          required: false
          type: text or  distance or  number
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: line
          in: formData
          description: A line is a point-to-point path consisting of two or more points.
            A line is expressed as a series of two or more point objects separated by
            space.
          required: false
          type: text
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: url or  creativework
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: polygon
          in: formData
          description: A polygon is the area enclosed by a point-to-point path for which
            the starting and ending points are the same. A polygon is expressed as a
            series of four or more space delimited points where the first and final
            points are identical.
          required: false
          type: text
        - name: postalcode
          in: formData
          description: The postal code. For example, 94043.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Geo Circle
    /geo-circle/{id}/:
      get:
        summary: Get Geo Circle
        description: Returns a single Geo Circle
        operationId: getGeoCircle
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Geo Circle
      put:
        summary: Update Geo Circle
        description: Update a single Geo Circle
        operationId: updateGeoCircleItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: address
          in: formData
          description: Physical address of the item.
          required: false
          type: text or  postaladdress
        - name: addresscountry
          in: formData
          description: The country. For example, USA. You can also provide the two-letter
            ISO 3166-1 alpha-2 country code.
          required: false
          type: text or  country
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: box
          in: formData
          description: A box is the area enclosed by the rectangle formed by two points.
            The first point is the lower corner, the second point is the upper corner.
            A box is expressed as two points separated by a space character.
          required: false
          type: text
        - name: circle
          in: formData
          description: A circle is the circular region of a specified radius centered
            at a specified latitude and longitude. A circle is expressed as a pair followed
            by a radius in meters.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: elevation
          in: formData
          description: The elevation of a location (WGS 84).
          required: false
          type: text or  number
        - name: geomidpoint
          in: formData
          description: Indicates the GeoCoordinates at the centre of a GeoShape e.g.
            GeoCircle.
          required: false
          type: geocoordinates
        - name: georadius
          in: formData
          description: Indicates the approximate radius of a GeoCircle (metres unless
            indicated otherwise via Distance notation).
          required: false
          type: text or  distance or  number
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: line
          in: formData
          description: A line is a point-to-point path consisting of two or more points.
            A line is expressed as a series of two or more point objects separated by
            space.
          required: false
          type: text
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: url or  creativework
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: polygon
          in: formData
          description: A polygon is the area enclosed by a point-to-point path for which
            the starting and ending points are the same. A polygon is expressed as a
            series of four or more space delimited points where the first and final
            points are identical.
          required: false
          type: text
        - name: postalcode
          in: formData
          description: The postal code. For example, 94043.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Geo Circle
      delete:
        summary: Geo Circle
        description: Deletes a single Geo Circle
        operationId: deleteGeoCircle
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Geo Circle
  definitions:
    item:
      properties:
      - name:
          description: additionaltype
          type: url
        description:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
      - name:
          description: address
          type: text or  postaladdress
        description:
          description: Physical address of the item.
          type: text or  postaladdress
      - name:
          description: addresscountry
          type: text or  country
        description:
          description: The country. For example, USA. You can also provide the two-letter
            ISO 3166-1 alpha-2 country code.
          type: text or  country
      - name:
          description: alternatename
          type: text
        description:
          description: An alias for the item.
          type: text
      - name:
          description: box
          type: text
        description:
          description: A box is the area enclosed by the rectangle formed by two points.
            The first point is the lower corner, the second point is the upper corner.
            A box is expressed as two points separated by a space character.
          type: text
      - name:
          description: circle
          type: text
        description:
          description: A circle is the circular region of a specified radius centered
            at a specified latitude and longitude. A circle is expressed as a pair followed
            by a radius in meters.
          type: text
      - name:
          description: description
          type: text
        description:
          description: A short description of the item.
          type: text
      - name:
          description: elevation
          type: text or  number
        description:
          description: The elevation of a location (WGS 84).
          type: text or  number
      - name:
          description: geomidpoint
          type: geocoordinates
        description:
          description: Indicates the GeoCoordinates at the centre of a GeoShape e.g.
            GeoCircle.
          type: geocoordinates
      - name:
          description: georadius
          type: text or  distance or  number
        description:
          description: Indicates the approximate radius of a GeoCircle (metres unless
            indicated otherwise via Distance notation).
          type: text or  distance or  number
      - name:
          description: image
          type: url or  imageobject
        description:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
      - name:
          description: line
          type: text
        description:
          description: A line is a point-to-point path consisting of two or more points.
            A line is expressed as a series of two or more point objects separated by
            space.
          type: text
      - name:
          description: mainentityofpage
          type: url or  creativework
        description:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: url or  creativework
      - name:
          description: name
          type: text
        description:
          description: The name of the item.
          type: text
      - name:
          description: polygon
          type: text
        description:
          description: A polygon is the area enclosed by a point-to-point path for which
            the starting and ending points are the same. A polygon is expressed as a
            series of four or more space delimited points where the first and final
            points are identical.
          type: text
      - name:
          description: postalcode
          type: text
        description:
          description: The postal code. For example, 94043.
          type: text
      - name:
          description: potentialaction
          type: action
        description:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          type: action
      - name:
          description: sameas
          type: url
        description:
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          type: url
      - name:
          description: url
          type: url
        description:
          description: URL of the item.
          type: url