- swagger: "2.0"
  info:
    title: Government Permit API
    description: A permit issued by a government agency.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: government.permit.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /government-permit/:
      get:
        summary: Get Government Permit
        description: Returns Government Permit
        operationId: getGovernmentPermit
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Government Permit
      post:
        summary: Add Government Permit
        description: Add Government Permit
        operationId: addGovernmentPermit
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: issuedby
          in: formData
          description: The organization issuing the ticket or permit.
          required: false
          type: organization
        - name: issuedthrough
          in: formData
          description: The service through with the permit was granted.
          required: false
          type: service
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: permitaudience
          in: formData
          description: The target audience for this permit.
          required: false
          type: audience
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        - name: validfor
          in: formData
          description: The time validity of the permit.
          required: false
          type: duration
        - name: validfrom
          in: formData
          description: The date when the item becomes valid.
          required: false
          type: datetime
        - name: validin
          in: formData
          description: The geographic area where the permit is valid.
          required: false
          type: administrativearea
        - name: validuntil
          in: formData
          description: The date when the item is no longer valid.
          required: false
          type: date
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Government Permit
    /government-permit/{id}/:
      get:
        summary: Get Government Permit
        description: Returns a single Government Permit
        operationId: getGovernmentPermit
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Government Permit
      put:
        summary: Update Government Permit
        description: Update a single Government Permit
        operationId: updateGovernmentPermitItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: issuedby
          in: formData
          description: The organization issuing the ticket or permit.
          required: false
          type: organization
        - name: issuedthrough
          in: formData
          description: The service through with the permit was granted.
          required: false
          type: service
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: permitaudience
          in: formData
          description: The target audience for this permit.
          required: false
          type: audience
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          required: false
          type: action
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        - name: validfor
          in: formData
          description: The time validity of the permit.
          required: false
          type: duration
        - name: validfrom
          in: formData
          description: The date when the item becomes valid.
          required: false
          type: datetime
        - name: validin
          in: formData
          description: The geographic area where the permit is valid.
          required: false
          type: administrativearea
        - name: validuntil
          in: formData
          description: The date when the item is no longer valid.
          required: false
          type: date
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Government Permit
      delete:
        summary: Government Permit
        description: Deletes a single Government Permit
        operationId: deleteGovernmentPermit
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/item'
        tags:
        - Government Permit
  definitions:
    item:
      properties:
      - name:
          description: additionaltype
          type: url
        description:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the 'typeof' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
      - name:
          description: alternatename
          type: text
        description:
          description: An alias for the item.
          type: text
      - name:
          description: description
          type: text
        description:
          description: A short description of the item.
          type: text
      - name:
          description: image
          type: url or  imageobject
        description:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
      - name:
          description: issuedby
          type: organization
        description:
          description: The organization issuing the ticket or permit.
          type: organization
      - name:
          description: issuedthrough
          type: service
        description:
          description: The service through with the permit was granted.
          type: service
      - name:
          description: mainentityofpage
          type: creativework or  url
        description:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
      - name:
          description: name
          type: text
        description:
          description: The name of the item.
          type: text
      - name:
          description: permitaudience
          type: audience
        description:
          description: The target audience for this permit.
          type: audience
      - name:
          description: potentialaction
          type: action
        description:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an 'object' role.
          type: action
      - name:
          description: sameas
          type: url
        description:
          description: URL of a reference Web page that unambiguously indicates the
            item's identity. E.g. the URL of the item's Wikipedia page, Freebase page,
            or official website.
          type: url
      - name:
          description: url
          type: url
        description:
          description: URL of the item.
          type: url
      - name:
          description: validfor
          type: duration
        description:
          description: The time validity of the permit.
          type: duration
      - name:
          description: validfrom
          type: datetime
        description:
          description: The date when the item becomes valid.
          type: datetime
      - name:
          description: validin
          type: administrativearea
        description:
          description: The geographic area where the permit is valid.
          type: administrativearea
      - name:
          description: validuntil
          type: date
        description:
          description: The date when the item is no longer valid.
          type: date