- swagger: "2.0"
  info:
    title: Medical Cause API
    description: The causative agent(s) that are responsible for the pathophysiologic
      process that eventually results in a medical condition, symptom or sign. In this
      schema, unless otherwise specified this is meant to be the proximate cause of
      the medical condition, symptom or sign. The proximate cause is defined as the
      causative agent that most directly results in the medical condition, symptom or
      sign. For example, the HIV virus could be considered a cause of AIDS. Or in a
      diagnostic context, if a patient fell and sustained a hip fracture and two days
      later sustained a pulmonary embolism which eventuated in a cardiac arrest, the
      cause of the cardiac arrest (the proximate cause) would be the pulmonary embolism
      and not the fall. Medical causes can include cardiovascular, chemical, dermatologic,
      endocrine, environmental, gastroenterologic, genetic, hematologic, gynecologic,
      iatrogenic, infectious, musculoskeletal, neurologic, nutritional, obstetric, oncologic,
      otolaryngologic, pharmacologic, psychiatric, pulmonary, renal, rheumatologic,
      toxic, traumatic, or urologic causes; medical conditions can be causes as well.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: medical.cause.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /medical-cause/:
      get:
        summary: Get Medical Cause
        description: Returns Medical Cause
        operationId: getMedicalCause
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalCause'
        tags:
        - Medical Cause
      post:
        summary: Add Medical Cause
        description: Add Medical Cause
        operationId: addMedicalCause
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: cause
          in: formData
          description: 'An underlying cause. More specifically, one of the causative
            agent(s) that are most directly responsible for the pathophysiologic process
            that eventually results in the occurrence. '
          required: false
          type: medicalcondition or medicalsignorsymptom
        - name: causeof
          in: formData
          description: The condition, complication, symptom, sign, etc. caused.
          required: false
          type: medicalentity
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalCause'
        tags:
        - Medical Cause
    /medical-cause/{id}/:
      get:
        summary: Get Medical Cause
        description: Returns a single Medical Cause
        operationId: getMedicalCause
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalCause'
        tags:
        - Medical Cause
      put:
        summary: Update Medical Cause
        description: Update a single Medical Cause
        operationId: updateMedicalCauseItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: cause
          in: formData
          description: 'An underlying cause. More specifically, one of the causative
            agent(s) that are most directly responsible for the pathophysiologic process
            that eventually results in the occurrence. '
          required: false
          type: medicalcondition or medicalsignorsymptom
        - name: causeof
          in: formData
          description: The condition, complication, symptom, sign, etc. caused.
          required: false
          type: medicalentity
        - name: code
          in: formData
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          required: false
          type: medicalcode
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: guideline
          in: formData
          description: A medical guideline related to this entity.
          required: false
          type: medicalguideline
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: url or  imageobject
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: medicinesystem
          in: formData
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          required: false
          type: medicinesystem
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: recognizingauthority
          in: formData
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          required: false
          type: organization
        - name: relevantspecialty
          in: formData
          description: If applicable, a medical specialty in which this entity is relevant.
          required: false
          type: medicalspecialty
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: study
          in: formData
          description: A medical study or trial related to this entity.
          required: false
          type: medicalstudy
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalCause'
        tags:
        - Medical Cause
      delete:
        summary: Medical Cause
        description: Deletes a single Medical Cause
        operationId: deleteMedicalCause
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/MedicalCause'
        tags:
        - Medical Cause
  definitions:
    MedicalCause:
      properties:
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        alternatename:
          description: An alias for the item.
          type: text
        cause:
          description: 'An underlying cause. More specifically, one of the causative
            agent(s) that are most directly responsible for the pathophysiologic process
            that eventually results in the occurrence. '
          type: medicalcondition or medicalsignorsymptom
        causeof:
          description: The condition, complication, symptom, sign, etc. caused.
          type: medicalentity
        code:
          description: A medical code for the entity, taken from a controlled vocabulary
            or ontology such as ICD-9, DiseasesDB, MeSH, SNOMED-CT, RxNorm, etc.
          type: medicalcode
        description:
          description: A short description of the item.
          type: text
        guideline:
          description: A medical guideline related to this entity.
          type: medicalguideline
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: url or  imageobject
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
        medicinesystem:
          description: The system of medicine that includes this MedicalEntity, for
            example \'evidence-based\', \'homeopathic\', \'chiropractic\', etc.
          type: medicinesystem
        name:
          description: The name of the item.
          type: text
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        recognizingauthority:
          description: If applicable, the organization that officially recognizes this
            entity as part of its endorsed system of medicine.
          type: organization
        relevantspecialty:
          description: If applicable, a medical specialty in which this entity is relevant.
          type: medicalspecialty
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        study:
          description: A medical study or trial related to this entity.
          type: medicalstudy
        url:
          description: URL of the item.
          type: url