- swagger: "2.0"
  info:
    title: Payment Charge Specification API
    description: The costs of settling the payment using a particular payment method.
    termsOfService: http://apievangelist.com/terms-of-service.html
    version: v1
  host: payment.charge.specification.example.com
  basePath: /
  schemes:
  - http
  produces:
  - application/json
  paths:
    /payment-charge-specification/:
      get:
        summary: Get Payment Charge Specification
        description: Returns Payment Charge Specification
        operationId: getPaymentChargeSpecification
        parameters:
        - name: q
          in: query
          description: Keyword search for item
          required: false
          type: string
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/PaymentChargeSpecification'
        tags:
        - Payment Charge Specification
      post:
        summary: Add Payment Charge Specification
        description: Add Payment Charge Specification
        operationId: addPaymentChargeSpecification
        parameters:
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: appliestodeliverymethod
          in: formData
          description: The delivery method(s) to which the delivery charge or payment
            charge specification applies.
          required: false
          type: deliverymethod
        - name: appliestopaymentmethod
          in: formData
          description: The payment method(s) to which the payment charge specification
            applies.
          required: false
          type: paymentmethod
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: eligiblequantity
          in: formData
          description: The interval and unit of measurement of ordering quantities for
            which the offer or price specification is valid. This allows e.g. specifying
            that a certain freight charge is valid only for a certain quantity.
          required: false
          type: quantitativevalue
        - name: eligibletransactionvolume
          in: formData
          description: The transaction volume, in a monetary unit, for which the offer
            or price specification is valid, e.g. for indicating a minimal purchasing
            volume, to express free shipping above a certain order volume, or to limit
            the acceptance of credit cards to purchases to a certain minimal amount.
          required: false
          type: pricespecification
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: imageobject or  url
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: maxprice
          in: formData
          description: The highest price if the price is a range.
          required: false
          type: number
        - name: minprice
          in: formData
          description: The lowest price if the price is a range.
          required: false
          type: number
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: price
          in: formData
          description: 'The offer price of a product, or of a price component when attached
            to PriceSpecification and its subtypes.      Usage guidelines:Use the priceCurrency
            property (with ISO 4217 codes e.g. \"USD\") instead of      including ambiguous
            symbols such as \''$\'' in the value.      Use \''.\'' (Unicode \''FULL
            STOP\'' (U+002E)) rather than \'',\'' to indicate a decimal point. Avoid
            using these symbols as a readability separator.      Note that both RDFa
            and Microdata syntax allow the use of a \"content=\" attribute for publishing
            simple machine-readable values      alongside more human-friendly formatting.      Use
            values from 0123456789 (Unicode \''DIGIT ZERO\'' (U+0030) to \''DIGIT NINE\''
            (U+0039)) rather than superficially similiar Unicode symbols.      '
          required: false
          type: number or  text
        - name: pricecurrency
          in: formData
          description: The currency (in 3-letter ISO 4217 format) of the price or a
            price component, when attached to PriceSpecification and its subtypes.
          required: false
          type: text
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        - name: validfrom
          in: formData
          description: The date when the item becomes valid.
          required: false
          type: datetime
        - name: validthrough
          in: formData
          description: The end of the validity of offer, price specification, or opening
            hours data.
          required: false
          type: datetime
        - name: valueaddedtaxincluded
          in: formData
          description: Specifies whether the applicable value-added tax (VAT) is included
            in the price specification or not.
          required: false
          type: boolean
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/PaymentChargeSpecification'
        tags:
        - Payment Charge Specification
    /payment-charge-specification/{id}/:
      get:
        summary: Get Payment Charge Specification
        description: Returns a single Payment Charge Specification
        operationId: getPaymentChargeSpecification
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/PaymentChargeSpecification'
        tags:
        - Payment Charge Specification
      put:
        summary: Update Payment Charge Specification
        description: Update a single Payment Charge Specification
        operationId: updatePaymentChargeSpecificationItem
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        - name: additionaltype
          in: formData
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          required: false
          type: url
        - name: alternatename
          in: formData
          description: An alias for the item.
          required: false
          type: text
        - name: appliestodeliverymethod
          in: formData
          description: The delivery method(s) to which the delivery charge or payment
            charge specification applies.
          required: false
          type: deliverymethod
        - name: appliestopaymentmethod
          in: formData
          description: The payment method(s) to which the payment charge specification
            applies.
          required: false
          type: paymentmethod
        - name: description
          in: formData
          description: A short description of the item.
          required: false
          type: text
        - name: eligiblequantity
          in: formData
          description: The interval and unit of measurement of ordering quantities for
            which the offer or price specification is valid. This allows e.g. specifying
            that a certain freight charge is valid only for a certain quantity.
          required: false
          type: quantitativevalue
        - name: eligibletransactionvolume
          in: formData
          description: The transaction volume, in a monetary unit, for which the offer
            or price specification is valid, e.g. for indicating a minimal purchasing
            volume, to express free shipping above a certain order volume, or to limit
            the acceptance of credit cards to purchases to a certain minimal amount.
          required: false
          type: pricespecification
        - name: image
          in: formData
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          required: false
          type: imageobject or  url
        - name: mainentityofpage
          in: formData
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          required: false
          type: creativework or  url
        - name: maxprice
          in: formData
          description: The highest price if the price is a range.
          required: false
          type: number
        - name: minprice
          in: formData
          description: The lowest price if the price is a range.
          required: false
          type: number
        - name: name
          in: formData
          description: The name of the item.
          required: false
          type: text
        - name: potentialaction
          in: formData
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          required: false
          type: action
        - name: price
          in: formData
          description: 'The offer price of a product, or of a price component when attached
            to PriceSpecification and its subtypes.      Usage guidelines:Use the priceCurrency
            property (with ISO 4217 codes e.g. \"USD\") instead of      including ambiguous
            symbols such as \''$\'' in the value.      Use \''.\'' (Unicode \''FULL
            STOP\'' (U+002E)) rather than \'',\'' to indicate a decimal point. Avoid
            using these symbols as a readability separator.      Note that both RDFa
            and Microdata syntax allow the use of a \"content=\" attribute for publishing
            simple machine-readable values      alongside more human-friendly formatting.      Use
            values from 0123456789 (Unicode \''DIGIT ZERO\'' (U+0030) to \''DIGIT NINE\''
            (U+0039)) rather than superficially similiar Unicode symbols.      '
          required: false
          type: number or  text
        - name: pricecurrency
          in: formData
          description: The currency (in 3-letter ISO 4217 format) of the price or a
            price component, when attached to PriceSpecification and its subtypes.
          required: false
          type: text
        - name: sameas
          in: formData
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          required: false
          type: url
        - name: url
          in: formData
          description: URL of the item.
          required: false
          type: url
        - name: validfrom
          in: formData
          description: The date when the item becomes valid.
          required: false
          type: datetime
        - name: validthrough
          in: formData
          description: The end of the validity of offer, price specification, or opening
            hours data.
          required: false
          type: datetime
        - name: valueaddedtaxincluded
          in: formData
          description: Specifies whether the applicable value-added tax (VAT) is included
            in the price specification or not.
          required: false
          type: boolean
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/PaymentChargeSpecification'
        tags:
        - Payment Charge Specification
      delete:
        summary: Payment Charge Specification
        description: Deletes a single Payment Charge Specification
        operationId: deletePaymentChargeSpecification
        parameters:
        - name: id
          in: path
          description: Unique id for item
          required: true
          type: integer
        responses:
          200:
            description: A successful response.
            schema:
              type: array
              items:
                $ref: '#/definitions/PaymentChargeSpecification'
        tags:
        - Payment Charge Specification
  definitions:
    PaymentChargeSpecification:
      properties:
        additionaltype:
          description: An additional type for the item, typically used for adding more
            specific types from external vocabularies in microdata syntax. This is a
            relationship between something and a class that the thing is in. In RDFa
            syntax, it is better to use the native RDFa syntax - the \'typeof\' attribute
            - for multiple types. Schema.org tools may have only weaker understanding
            of extra types, in particular those defined externally.
          type: url
        alternatename:
          description: An alias for the item.
          type: text
        appliestodeliverymethod:
          description: The delivery method(s) to which the delivery charge or payment
            charge specification applies.
          type: deliverymethod
        appliestopaymentmethod:
          description: The payment method(s) to which the payment charge specification
            applies.
          type: paymentmethod
        description:
          description: A short description of the item.
          type: text
        eligiblequantity:
          description: The interval and unit of measurement of ordering quantities for
            which the offer or price specification is valid. This allows e.g. specifying
            that a certain freight charge is valid only for a certain quantity.
          type: quantitativevalue
        eligibletransactionvolume:
          description: The transaction volume, in a monetary unit, for which the offer
            or price specification is valid, e.g. for indicating a minimal purchasing
            volume, to express free shipping above a certain order volume, or to limit
            the acceptance of credit cards to purchases to a certain minimal amount.
          type: pricespecification
        image:
          description: An image of the item. This can be a URL or a fully described
            ImageObject.
          type: imageobject or  url
        mainentityofpage:
          description: 'Indicates a page (or other CreativeWork) for which this thing
            is the main entity being described.            See background notes for
            details.       Inverse property: mainEntity.'
          type: creativework or  url
        maxprice:
          description: The highest price if the price is a range.
          type: number
        minprice:
          description: The lowest price if the price is a range.
          type: number
        name:
          description: The name of the item.
          type: text
        potentialaction:
          description: Indicates a potential Action, which describes an idealized action
            in which this thing would play an \'object\' role.
          type: action
        price:
          description: 'The offer price of a product, or of a price component when attached
            to PriceSpecification and its subtypes.      Usage guidelines:Use the priceCurrency
            property (with ISO 4217 codes e.g. \"USD\") instead of      including ambiguous
            symbols such as \''$\'' in the value.      Use \''.\'' (Unicode \''FULL
            STOP\'' (U+002E)) rather than \'',\'' to indicate a decimal point. Avoid
            using these symbols as a readability separator.      Note that both RDFa
            and Microdata syntax allow the use of a \"content=\" attribute for publishing
            simple machine-readable values      alongside more human-friendly formatting.      Use
            values from 0123456789 (Unicode \''DIGIT ZERO\'' (U+0030) to \''DIGIT NINE\''
            (U+0039)) rather than superficially similiar Unicode symbols.      '
          type: number or  text
        pricecurrency:
          description: The currency (in 3-letter ISO 4217 format) of the price or a
            price component, when attached to PriceSpecification and its subtypes.
          type: text
        sameas:
          description: URL of a reference Web page that unambiguously indicates the
            item\'s identity. E.g. the URL of the item\'s Wikipedia page, Freebase page,
            or official website.
          type: url
        url:
          description: URL of the item.
          type: url
        validfrom:
          description: The date when the item becomes valid.
          type: datetime
        validthrough:
          description: The end of the validity of offer, price specification, or opening
            hours data.
          type: datetime
        valueaddedtaxincluded:
          description: Specifies whether the applicable value-added tax (VAT) is included
            in the price specification or not.
          type: boolean