- "{\n\t\"swagger\": \"2.0\",\n\t\"info\": {\n\t\t\"title\": \"Type And Quantity
    Node API\",\n\t\t\"description\": \"A structured value indicating the quantity,
    unit of measurement, and business function of goods included in a bundle offer.\",\n\t\t\"termsOfService\":
    \"http://apievangelist.com/terms-of-service.html\",\n\t\t\"version\": \"v1\"\n\t},\n\t\"host\":
    \"type.and.quantity.node.example.com\",\n\t\"basePath\": \"/\",\n\t\"schemes\":
    [\"http\"],\n\t\"produces\": [\"application/json\"],\n\t\"paths\": {\n\t\t\"/type-and-quantity-node/\":
    {\n\t\t\t\"get\": {\n\t\t\t\t\"summary\": \"Get Type And Quantity Node\",\n\t\t\t\t\"description\":
    \"Returns Type And Quantity Node\",\n\t\t\t\t\"operationId\": \"getTypeAndQuantityNode\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"q\",\n\t\t\t\t\t\"in\": \"query\",\n\t\t\t\t\t\"description\":
    \"Keyword search for item\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"string\"\n\t\t\t\t}],\n\t\t\t\t\"responses\": {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\":
    \"A successful response.\",\n\t\t\t\t\t\t\"schema\": {\n\t\t\t\t\t\t\t\"type\":
    \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\": \"#/definitions/TypeAndQuantityNode\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Type And Quantity Node\"]\n\t\t\t},\n\t\t\t\"post\": {\n\t\t\t\t\"summary\":
    \"Add Type And Quantity Node\",\n\t\t\t\t\"description\": \"Add Type And Quantity
    Node\",\n\t\t\t\t\"operationId\": \"addTypeAndQuantityNode\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"additionaltype\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"An additional type for the item, typically used for adding more specific types
    from external vocabularies in microdata syntax. This is a relationship between something
    and a class that the thing is in. In RDFa syntax, it is better to use the native
    RDFa syntax - the \\'typeof\\' attribute - for multiple types. Schema.org tools
    may have only weaker understanding of extra types, in particular those defined externally.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"alternatename\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"An alias for the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"amountofthisgood\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The quantity of the goods included in
    the offer.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"number\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"businessfunction\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"The business function (e.g. sell, lease, repair, dispose) of the offer or component
    of a bundle (TypeAndQuantityNode). The default is http://purl.org/goodrelations/v1#Sell.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"businessfunction\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"description\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"A
    short description of the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"image\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"An image of the item. This can be a
    URL or a fully described ImageObject.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"url or  imageobject\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"includesobject\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"This links to a node or nodes indicating
    the exact quantity of the products included in the offer. \",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"demand or offer\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"mainentityofpage\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a page (or other CreativeWork) for which this thing is the main entity
    being described.            See background notes for details.       Inverse property:
    mainEntity.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"creativework
    or  url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"name\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The name of the item.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"potentialaction\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a potential Action, which describes an idealized action in which this
    thing would play an \\'object\\' role.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"action\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"sameas\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"URL of a reference Web page that unambiguously
    indicates the item\\'s identity. E.g. the URL of the item\\'s Wikipedia page, Freebase
    page, or official website.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"typeofgood\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The product that this structured value
    is referring to.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"product\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"unitcode\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"The
    unit of measurement given using the UN/CEFACT Common Code (3 characters) or a URL.
    Other codes than the UN/CEFACT Common Code may be used with a prefix followed by
    a colon.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"text or  url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"unittext\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"A string
    or text indicating the unit of measurement. Useful if you cannot provide a standard
    unit code forunitCode.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"url\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"URL of the
    item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t}],\n\t\t\t\t\"responses\":
    {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/TypeAndQuantityNode\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Type And Quantity Node\"]\n\t\t\t}\n\t\t},\n\t\t\"/type-and-quantity-node/{id}/\":
    {\n\t\t\t\"get\": {\n\t\t\t\t\"summary\": \"Get Type And Quantity Node\",\n\t\t\t\t\"description\":
    \"Returns a single Type And Quantity Node\",\n\t\t\t\t\"operationId\": \"getTypeAndQuantityNode\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"id\",\n\t\t\t\t\t\"in\": \"path\",\n\t\t\t\t\t\"description\":
    \"Unique id for item\",\n\t\t\t\t\t\"required\": true,\n\t\t\t\t\t\"type\": \"integer\"\n\t\t\t\t}],\n\t\t\t\t\"responses\":
    {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/TypeAndQuantityNode\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Type And Quantity Node\"]\n\t\t\t},\n\t\t\t\"put\": {\n\t\t\t\t\"summary\": \"Update
    Type And Quantity Node\",\n\t\t\t\t\"description\": \"Update a single Type And Quantity
    Node\",\n\t\t\t\t\"operationId\": \"updateTypeAndQuantityNodeItem\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"id\",\n\t\t\t\t\t\"in\": \"path\",\n\t\t\t\t\t\"description\":
    \"Unique id for item\",\n\t\t\t\t\t\"required\": true,\n\t\t\t\t\t\"type\": \"integer\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"additionaltype\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"An additional type for the item, typically used for adding more specific types
    from external vocabularies in microdata syntax. This is a relationship between something
    and a class that the thing is in. In RDFa syntax, it is better to use the native
    RDFa syntax - the \\'typeof\\' attribute - for multiple types. Schema.org tools
    may have only weaker understanding of extra types, in particular those defined externally.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"alternatename\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"An alias for the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"amountofthisgood\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The quantity of the goods included in
    the offer.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"number\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"businessfunction\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"The business function (e.g. sell, lease, repair, dispose) of the offer or component
    of a bundle (TypeAndQuantityNode). The default is http://purl.org/goodrelations/v1#Sell.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"businessfunction\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"description\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"A
    short description of the item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"image\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"An image of the item. This can be a
    URL or a fully described ImageObject.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"url or  imageobject\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"includesobject\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"This links to a node or nodes indicating
    the exact quantity of the products included in the offer. \",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"demand or offer\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"mainentityofpage\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a page (or other CreativeWork) for which this thing is the main entity
    being described.            See background notes for details.       Inverse property:
    mainEntity.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"creativework
    or  url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"name\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The name of the item.\",\n\t\t\t\t\t\"required\":
    false,\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"potentialaction\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\":
    \"Indicates a potential Action, which describes an idealized action in which this
    thing would play an \\'object\\' role.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"action\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"sameas\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"URL of a reference Web page that unambiguously
    indicates the item\\'s identity. E.g. the URL of the item\\'s Wikipedia page, Freebase
    page, or official website.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\": \"typeofgood\",\n\t\t\t\t\t\"in\":
    \"formData\",\n\t\t\t\t\t\"description\": \"The product that this structured value
    is referring to.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"product\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"unitcode\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"The
    unit of measurement given using the UN/CEFACT Common Code (3 characters) or a URL.
    Other codes than the UN/CEFACT Common Code may be used with a prefix followed by
    a colon.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"text or  url\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"unittext\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"A string
    or text indicating the unit of measurement. Useful if you cannot provide a standard
    unit code forunitCode.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t{\n\t\t\t\t\t\"name\":
    \"url\",\n\t\t\t\t\t\"in\": \"formData\",\n\t\t\t\t\t\"description\": \"URL of the
    item.\",\n\t\t\t\t\t\"required\": false,\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t}],\n\t\t\t\t\"responses\":
    {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/TypeAndQuantityNode\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Type And Quantity Node\"]\n\t\t\t},\n\t\t\t\"delete\": {\n\t\t\t\t\"summary\":
    \"Type And Quantity Node\",\n\t\t\t\t\"description\": \"Deletes a single Type And
    Quantity Node\",\n\t\t\t\t\"operationId\": \"deleteTypeAndQuantityNode\",\n\t\t\t\t\"parameters\":
    [{\n\t\t\t\t\t\"name\": \"id\",\n\t\t\t\t\t\"in\": \"path\",\n\t\t\t\t\t\"description\":
    \"Unique id for item\",\n\t\t\t\t\t\"required\": true,\n\t\t\t\t\t\"type\": \"integer\"\n\t\t\t\t}],\n\t\t\t\t\"responses\":
    {\n\t\t\t\t\t\"200\": {\n\t\t\t\t\t\t\"description\": \"A successful response.\",\n\t\t\t\t\t\t\"schema\":
    {\n\t\t\t\t\t\t\t\"type\": \"array\",\n\t\t\t\t\t\t\t\"items\": {\n\t\t\t\t\t\t\t\t\"$ref\":
    \"#/definitions/TypeAndQuantityNode\"\n\t\t\t\t\t\t\t}\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"tags\":
    [\"Type And Quantity Node\"]\n\t\t\t}\n\t\t}\n\t},\n\t\"definitions\": {\n\t\t\"TypeAndQuantityNode\":
    {\n\t\t\t\"properties\": {\n\t\t\t\t\"additionaltype\": {\n\t\t\t\t\t\"description\":
    \"An additional type for the item, typically used for adding more specific types
    from external vocabularies in microdata syntax. This is a relationship between something
    and a class that the thing is in. In RDFa syntax, it is better to use the native
    RDFa syntax - the \\'typeof\\' attribute - for multiple types. Schema.org tools
    may have only weaker understanding of extra types, in particular those defined externally.\",\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t\"alternatename\": {\n\t\t\t\t\t\"description\": \"An
    alias for the item.\",\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t\"amountofthisgood\":
    {\n\t\t\t\t\t\"description\": \"The quantity of the goods included in the offer.\",\n\t\t\t\t\t\"type\":
    \"number\"\n\t\t\t\t},\n\t\t\t\t\"businessfunction\": {\n\t\t\t\t\t\"description\":
    \"The business function (e.g. sell, lease, repair, dispose) of the offer or component
    of a bundle (TypeAndQuantityNode). The default is http://purl.org/goodrelations/v1#Sell.\",\n\t\t\t\t\t\"type\":
    \"businessfunction\"\n\t\t\t\t},\n\t\t\t\t\"description\": {\n\t\t\t\t\t\"description\":
    \"A short description of the item.\",\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t\"image\":
    {\n\t\t\t\t\t\"description\": \"An image of the item. This can be a URL or a fully
    described ImageObject.\",\n\t\t\t\t\t\"type\": \"url or  imageobject\"\n\t\t\t\t},\n\t\t\t\t\"includesobject\":
    {\n\t\t\t\t\t\"description\": \"This links to a node or nodes indicating the exact
    quantity of the products included in the offer. \",\n\t\t\t\t\t\"type\": \"demand
    or offer\"\n\t\t\t\t},\n\t\t\t\t\"mainentityofpage\": {\n\t\t\t\t\t\"description\":
    \"Indicates a page (or other CreativeWork) for which this thing is the main entity
    being described.            See background notes for details.       Inverse property:
    mainEntity.\",\n\t\t\t\t\t\"type\": \"creativework or  url\"\n\t\t\t\t},\n\t\t\t\t\"name\":
    {\n\t\t\t\t\t\"description\": \"The name of the item.\",\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t\"potentialaction\":
    {\n\t\t\t\t\t\"description\": \"Indicates a potential Action, which describes an
    idealized action in which this thing would play an \\'object\\' role.\",\n\t\t\t\t\t\"type\":
    \"action\"\n\t\t\t\t},\n\t\t\t\t\"sameas\": {\n\t\t\t\t\t\"description\": \"URL
    of a reference Web page that unambiguously indicates the item\\'s identity. E.g.
    the URL of the item\\'s Wikipedia page, Freebase page, or official website.\",\n\t\t\t\t\t\"type\":
    \"url\"\n\t\t\t\t},\n\t\t\t\t\"typeofgood\": {\n\t\t\t\t\t\"description\": \"The
    product that this structured value is referring to.\",\n\t\t\t\t\t\"type\": \"product\"\n\t\t\t\t},\n\t\t\t\t\"unitcode\":
    {\n\t\t\t\t\t\"description\": \"The unit of measurement given using the UN/CEFACT
    Common Code (3 characters) or a URL. Other codes than the UN/CEFACT Common Code
    may be used with a prefix followed by a colon.\",\n\t\t\t\t\t\"type\": \"text or
    \ url\"\n\t\t\t\t},\n\t\t\t\t\"unittext\": {\n\t\t\t\t\t\"description\": \"A string
    or text indicating the unit of measurement. Useful if you cannot provide a standard
    unit code forunitCode.\",\n\t\t\t\t\t\"type\": \"text\"\n\t\t\t\t},\n\t\t\t\t\"url\":
    {\n\t\t\t\t\t\"description\": \"URL of the item.\",\n\t\t\t\t\t\"type\": \"url\"\n\t\t\t\t}\n\t\t\t}\n\t\t}\n\t}\n}"